version: '2'
services:
    frontend:
        depends_on:
            - 'api'
        build: ./diamonds-viewer
        ports:
            - '80:80'
        links:
            - api
    api:
        depends_on:
            - 'mongo'
        build: ./diamonds-api
    mongo:
        image: 'mongo:3.4.6'
        ports:
            - '27017:27017'
        volumes:
            - 'mongo:/data/db'

volumes:
    mongo:

