version: '2'
services:
    frontend:
        depends_on:
            - 'api'
        build: ./diamonds-viewer
        ports:
            - '80:80'
        links:
            - api
    api:
        depends_on:
            - 'mongo'
        build: ./diamonds-api
        links:
            - mongo
    mongo:
        image: 'mongo:3.4.6'
        volumes:
            - 'mongo:/data/db'

volumes:
    mongo:

